default:
    image: alpine:latest

variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build
    - docs

build:
    stage: build
    before_script:
        - apk update && apk upgrade
        - apk add build-base cmake
    script:
        - mkdir build
        - cmake -B build -DCMAKE_BUILD_TYPE=Release
        - make -C build knocknock knocknock_unittest
        - ./build/src/unittests/knocknock_unittest -r junit -o test_result.xml
    artifacts:
        reports:
            junit: test_result.xml

pages:
    stage: docs
    before_script:
        - apk update && apk upgrade
        - apk add doxygen
    script:
        - doxygen
        - mv public/html/* public/
        - rmdir public/html
    only:
        - master
    artifacts:
        paths:
            - public
